[package]
name = "p2p-lib"
version = "0.0.1"
edition = "2021"
authors = ["Iquiji <me@example.com>"]

[dependencies]
tokio = {version= "1.16",features=["full"]}
chrono = "0.4"
eyre = "0.6"

parking_lot = "0.12"

blake2 = "0.10.2"

rand = "0.8"